import crypto from 'crypto';

export type RegressionMetrics={quality:number|null;consistency:number|null;costUsd:number;latencyMs:number;errorRate:number;outputHashes:Record<string,string>};
export type RegressionThresholds={qualityDrop:number;consistencyDrop:number;costIncreasePct:number;latencyIncreasePct:number;errorRateIncrease:number};

const avg=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const pct=(current:number,baseline:number)=>baseline>0?((current-baseline)/baseline)*100:current>0?100:0;
export function hashRegressionOutput(value:unknown){return crypto.createHash('sha256').update(JSON.stringify(value??null)).digest('hex').slice(0,16)}
export function aggregateRegressionRuns(runs:Array<{caseKey:string;status:string;costUsd?:number|null;durationMs?:number|null;quality?:number|null;consistency?:number|null;output?:unknown}>):RegressionMetrics{const completed=runs.filter(run=>run.status==='completed'),quality=completed.flatMap(run=>typeof run.quality==='number'?[run.quality]:[]),consistency=completed.flatMap(run=>typeof run.consistency==='number'?[run.consistency]:[]);return{quality:quality.length?avg(quality):null,consistency:consistency.length?avg(consistency):null,costUsd:avg(completed.map(run=>run.costUsd||0)),latencyMs:avg(completed.map(run=>run.durationMs||0)),errorRate:runs.length?(runs.length-completed.length)/runs.length:0,outputHashes:Object.fromEntries(completed.map(run=>[run.caseKey,hashRegressionOutput(run.output)]))}}
export function compareRegression(baseline:RegressionMetrics,candidate:RegressionMetrics,thresholds:RegressionThresholds){const deltas={quality:baseline.quality!==null&&candidate.quality!==null?candidate.quality-baseline.quality:null,consistency:baseline.consistency!==null&&candidate.consistency!==null?candidate.consistency-baseline.consistency:null,costPct:pct(candidate.costUsd,baseline.costUsd),latencyPct:pct(candidate.latencyMs,baseline.latencyMs),errorRate:candidate.errorRate-baseline.errorRate,changedOutputs:Object.keys(candidate.outputHashes).filter(key=>candidate.outputHashes[key]!==baseline.outputHashes[key]).length};const reasons:string[]=[];if(deltas.quality!==null&&deltas.quality < -thresholds.qualityDrop)reasons.push(`Calidad ${Math.abs(deltas.quality).toFixed(1)} puntos menor`);if(deltas.consistency!==null&&deltas.consistency < -thresholds.consistencyDrop)reasons.push(`Consistencia ${Math.abs(deltas.consistency).toFixed(1)} puntos menor`);if(deltas.costPct>thresholds.costIncreasePct)reasons.push(`Costo ${deltas.costPct.toFixed(1)}% mayor`);if(deltas.latencyPct>thresholds.latencyIncreasePct)reasons.push(`Latencia ${deltas.latencyPct.toFixed(1)}% mayor`);if(deltas.errorRate>thresholds.errorRateIncrease)reasons.push(`Errores ${(deltas.errorRate*100).toFixed(1)} puntos porcentuales mayores`);return{degraded:reasons.length>0,reasons,deltas}}
