export type WebTagCategory = {
  name: string;
  description: string;
  icon: string;
  kind: 'tag' | 'stack' | 'membership';
  tags: string[];
};

export const webTagCategoryDefs: WebTagCategory[] = [
  {
    name: 'Page Type',
    description: 'Landing layouts, clones, SaaS, and site patterns',
    icon: 'LayoutGrid',
    kind: 'tag',
    tags: [
      'landing page',
      'clone',
      'SaaS',
      'marketplace',
      'portfolio',
      'architecture',
      'DevTool',
      'streaming',
      'productivity',
      'no-code',
      'community',
      'collaboration',
      'payments',
      'retail',
      'education',
      'enterprise',
      'travel',
      'creative',
      'gaming',
      'social',
      'recruitment',
      'design',
      'music',
      'fintech',
      'ecommerce',
      'wellness',
      'health',
      'developer tools',
      'observability',
      'AI',
    ],
  },
  {
    name: 'Style & Theme',
    description: 'Visual direction, color modes, and UI aesthetics',
    icon: 'Palette',
    kind: 'tag',
    tags: [
      'dark mode',
      'light mode',
      'minimalist',
      'brutalism',
      'neon',
      'glassmorphism',
      'editorial',
      'cyberpunk',
      'synthwave',
      'warm',
      'gradient',
      'FAQ',
      'pricing',
      'carousel',
      'terminal',
      'dark',
      'light',
      'pastel',
      'cinematic',
      'corporate',
      'luxury',
      'playful',
      'bold',
      'elegant',
      'modern',
      'vintage',
      'responsive',
      'HTML',
      'CSS',
    ],
  },
  {
    name: 'Industry & Use Case',
    description: 'Verticals and product categories',
    icon: 'Building2',
    kind: 'tag',
    tags: [
      'food delivery',
      'freelance',
      'CRM',
      'social media',
      'inbound marketing',
      'Kanban',
      'scheduling',
      'signatures',
      'whiteboard',
      'Agile',
      'DevOps',
      'API',
      'data',
      'security',
      'automation',
      'forms',
      'newsletters',
      'animation',
      'sport',
      'fitness',
      'meditation',
      'courses',
      'anime',
      'hospitality',
      'coworking',
      'pets',
      'events',
      'gardening',
      'outdoor',
      'therapy',
    ],
  },
  {
    name: 'Tech Stack',
    description: 'Implementation technologies used in demos',
    icon: 'Code2',
    kind: 'stack',
    tags: [
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'Next.js 14',
      'Tailwind',
      'Tailwind CSS',
      'Tailwind CDN',
      'shadcn/ui',
      'Framer Motion',
      'Leaflet',
    ],
  },
  {
    name: 'Membership',
    description: 'Access tier for prompts and demos',
    icon: 'Crown',
    kind: 'membership',
    tags: ['Premium'],
  },
];
