'use client';
import { useState } from 'react';
import Header from '@/components/layout/header';import Footer from '@/components/layout/footer';
import { Badge } from '@/components/ui/badge';import { Button } from '@/components/ui/button';import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';import { Checkbox } from '@/components/ui/checkbox';import { Textarea } from '@/components/ui/textarea';
import { ArrowRight,Check,Clipboard,Sparkles } from 'lucide-react';
type Goal='lower-cost'|'consistency'|'realism'|'fewer-hallucinations'|'structured-output'|'provider-adaptation'|'translation';
type Result={optimizedPrompt:string;summary:string;changes:Array<{goal:Goal;change:string;reason:string}>;preservedIntent:string[];warnings:string[]};
const goals:Array<{id:Goal;label:string;description:string}>=[{id:'lower-cost',label:'Menor costo',description:'Elimina redundancia y limita salida innecesaria.'},{id:'consistency',label:'Mayor consistencia',description:'Aclara pasos, restricciones y criterios.'},{id:'realism',label:'Mejor realismo',description:'Añade dirección plausible y controlada.'},{id:'fewer-hallucinations',label:'Menos alucinaciones',description:'Exige límites, evidencia e incertidumbre.'},{id:'structured-output',label:'Respuesta estructurada',description:'Define un esquema de salida estricto.'},{id:'provider-adaptation',label:'Adaptar proveedor',description:'Ajusta el prompt al modelo de destino.'},{id:'translation',label:'Traducir conservando intención',description:'Conserva variables, nombres y restricciones.'}];
export default function PromptOptimizerClient(){const[prompt,setPrompt]=useState(''),[selected,setSelected]=useState<Goal[]>(['consistency']),[source,setSource]=useState('generic'),[target,setTarget]=useState('gemini'),[language,setLanguage]=useState('same as source'),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const toggle=(id:Goal)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const submit=async()=>{setBusy(true);setError('');setResult(null);const response=await fetch('/api/prompt-optimizer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,goals:selected,sourceProvider:source,targetProvider:target,targetLanguage:language})});const data=await response.json().catch(()=>({}));if(response.ok)setResult(data.result);else setError(data.error||'No se pudo optimizar.');setBusy(false)};
 return <div className="flex min-h-screen flex-col"><Header/><main className="container flex-1 py-10"><div className="mx-auto max-w-6xl space-y-6"><div><Badge variant="secondary" className="mb-3 gap-1"><Sparkles className="size-3"/>Optimización dirigida</Badge><h1 className="text-3xl font-bold md:text-4xl">Optimiza el prompt con un objetivo claro</h1><p className="mt-2 text-muted-foreground">Conserva la intención original y revisa cada modificación antes de utilizarla.</p></div><Card><CardContent className="space-y-5 p-5"><label className="space-y-2"><span className="font-semibold">Prompt original</span><Textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={20000} className="min-h-52 font-mono text-xs"/></label><div><p className="mb-3 font-semibold">Objetivos</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{goals.map(goal=><label key={goal.id} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${selected.includes(goal.id)?'border-primary bg-primary/5':''}`}><Checkbox checked={selected.includes(goal.id)} onCheckedChange={()=>toggle(goal.id)}/><span><strong className="block text-sm">{goal.label}</strong><span className="text-xs text-muted-foreground">{goal.description}</span></span></label>)}</div></div><div className="grid gap-3 sm:grid-cols-3"><Select label="Proveedor original" value={source} onChange={setSource} options={['generic','gemini','openai','anthropic']}/><Select label="Proveedor destino" value={target} onChange={setTarget} options={['generic','gemini','openai','anthropic']}/><Select label="Idioma destino" value={language} onChange={setLanguage} options={['same as source','Español','English','Português','Français']}/></div><Button onClick={submit} disabled={busy||prompt.trim().length<10||selected.length===0}><Sparkles className="mr-2 size-4"/>{busy?'Optimizando…':'Optimizar prompt'}</Button>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</CardContent></Card>
 {result&&<><div className="grid gap-5 lg:grid-cols-[1fr_auto_1fr]"><PromptPanel title="Antes" content={prompt}/><ArrowRight className="mx-auto hidden self-center text-muted-foreground lg:block"/><PromptPanel title="Después" content={result.optimizedPrompt} copy/></div><Card><CardHeader><CardTitle>Por qué cambió</CardTitle></CardHeader><CardContent className="space-y-4"><p>{result.summary}</p><div className="grid gap-3 md:grid-cols-2">{result.changes.map((change,index)=><div key={`${change.goal}-${index}`} className="rounded-xl border p-4"><Badge variant="outline">{goals.find(g=>g.id===change.goal)?.label||change.goal}</Badge><p className="mt-2 text-sm font-semibold">{change.change}</p><p className="mt-1 text-xs text-muted-foreground">{change.reason}</p></div>)}</div><div><h3 className="mb-2 flex items-center gap-2 font-semibold"><Check className="size-4 text-emerald-500"/>Intención preservada</h3><ul className="list-inside list-disc text-sm text-muted-foreground">{result.preservedIntent.map(item=><li key={item}>{item}</li>)}</ul></div>{result.warnings.length>0&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4"><strong>Revisa antes de usar</strong><ul className="mt-2 list-inside list-disc text-sm">{result.warnings.map(item=><li key={item}>{item}</li>)}</ul></div>}</CardContent></Card></>}</div></main><Footer/></div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="space-y-1 text-sm"><span className="font-medium">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3">{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function PromptPanel({title,content,copy=false}:{title:string;content:string;copy?:boolean}){return <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>{title}</CardTitle>{copy&&<Button size="sm" variant="ghost" onClick={()=>navigator.clipboard.writeText(content)}><Clipboard className="mr-2 size-4"/>Copiar</Button>}</div></CardHeader><CardContent><pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap rounded-lg bg-muted p-4 text-xs">{content}</pre></CardContent></Card>}
