import { createZipArchive } from '@/lib/zip-archive';
import { getServerSubscriptionStatus, hasDownloadPlan } from '@/lib/server-subscription-status';
import { NextResponse } from 'next/server';

export const runtime = 'nodejs';

type ComposerPayload = {
  projectName: string; brand: string; description: string; primary: string; secondary: string; background: string;
  includeSidebar: boolean;
  selections: Record<'header'|'sidebar'|'hero'|'card'|'form'|'button'|'footer', { id:string; title:string; prompt:string }>;
  masterPrompt: string;
};
const clean=(value:unknown,max=300)=>typeof value==='string'?value.trim().slice(0,max):'';
const color=(value:unknown,fallback:string)=>/^#[0-9a-f]{6}$/i.test(clean(value,7))?clean(value,7):fallback;
const slug=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,50)||'composed-site';
const jsxText=(value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('{','&#123;').replaceAll('}','&#125;');

function parse(body:unknown):ComposerPayload|null{
  if(!body||typeof body!=='object')return null;const raw=body as Record<string,unknown>,rawSelections=raw.selections;
  if(!rawSelections||typeof rawSelections!=='object')return null;const selections={} as ComposerPayload['selections'];
  for(const key of ['header','sidebar','hero','card','form','button','footer'] as const){const item=(rawSelections as Record<string,unknown>)[key];if(!item||typeof item!=='object')return null;const entry=item as Record<string,unknown>;selections[key]={id:clean(entry.id,80),title:clean(entry.title,160),prompt:clean(entry.prompt,8000)};if(!selections[key].id||!selections[key].title)return null;}
  const masterPrompt=clean(raw.masterPrompt,30000);
  return{projectName:(clean(raw.projectName,80)||'Composed Site').replace(/[\\']/g,''),brand:clean(raw.brand,80)||'Nova',description:(clean(raw.description,300)||'A coherent digital experience.').replace(/[\\']/g,''),primary:color(raw.primary,'#7c3aed'),secondary:color(raw.secondary,'#06b6d4'),background:color(raw.background,'#09090b'),includeSidebar:typeof raw.includeSidebar==='boolean'?raw.includeSidebar:masterPrompt.includes('Header, Sidebar, Hero'),selections,masterPrompt};
}
function component(name:string,body:string){return `'use client';\n\nexport function ${name}(){return (${body});}\n`;}
function files(config:ComposerPayload){const s=config.selections;const componentNames={header:'SiteHeader',sidebar:'SiteSidebar',hero:'HeroSection',card:'FeatureCards',form:'LeadForm',button:'PrimaryButton',footer:'SiteFooter'} as const;const chosen=Object.entries(s).map(([key,value])=>`- ${key}: ${value.title} (${value.id})`).join('\n');
  const safeBrand=jsxText(config.brand),safeProject=jsxText(config.projectName),safeDescription=jsxText(config.description);
  const sidebarImport=config.includeSidebar?`import { SiteSidebar } from '@/components/site-sidebar';\n`:'';
  const sidebarMarkup=config.includeSidebar?'<SiteSidebar/>':'';
  const page=`import { SiteHeader } from '@/components/site-header';\n${sidebarImport}import { HeroSection } from '@/components/hero-section';\nimport { FeatureCards } from '@/components/feature-cards';\nimport { LeadForm } from '@/components/lead-form';\nimport { PrimaryButton } from '@/components/primary-button';\nimport { SiteFooter } from '@/components/site-footer';\n\nexport default function Page(){return <div className="min-h-screen bg-background text-foreground"><SiteHeader/><div className="mx-auto flex max-w-7xl">${sidebarMarkup}<main className="min-w-0 flex-1"><HeroSection/><FeatureCards/><LeadForm/><section className="px-6 pb-20 text-center"><PrimaryButton/></section></main></div><SiteFooter/></div>}\n`;
  const header=component(componentNames.header,`<header className="sticky top-0 z-50 border-b border-white/10 bg-background/85 backdrop-blur-xl"><nav className="mx-auto flex h-16 max-w-7xl items-center px-5"><strong className="text-xl">${safeBrand}</strong><div className="ml-auto hidden gap-6 text-sm md:flex"><a href="#features">Features</a><a href="#contact">Contact</a></div><a href="#contact" className="ml-5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">Get started</a></nav></header>`);
  const sidebar=component(componentNames.sidebar,`<aside className="sticky top-20 hidden h-[calc(100vh-6rem)] w-52 shrink-0 p-4 lg:block"><nav className="space-y-1 rounded-2xl border border-white/10 bg-card p-3">{['Overview','Solutions','Resources'].map((item,index)=><a key={item} href={index===0?'#':'#features'} className={\`block rounded-xl px-3 py-2 text-sm \${index===0?'bg-primary text-white':''}\`}>{item}</a>)}</nav></aside>`);
  const hero=component(componentNames.hero,`<section className="relative overflow-hidden px-6 py-28 text-center"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_50%_30%,var(--secondary),transparent_35%)] opacity-25"/><p className="text-xs font-black uppercase tracking-[.25em] text-primary">${jsxText(s.hero.title)}</p><h1 className="mx-auto mt-5 max-w-4xl text-5xl font-black tracking-tight md:text-7xl">${safeProject}</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-muted">${safeDescription}</p><a href="#contact" className="mt-8 inline-flex rounded-xl bg-primary px-6 py-3 font-bold text-white">Start now</a></section>`);
  const cards=component(componentNames.card,`<section id="features" className="grid gap-5 px-6 py-16 md:grid-cols-3">{['Focused experience','Responsive system','Ready to scale'].map((title,index)=><article key={title} className="rounded-3xl border border-white/10 bg-card p-6 shadow-xl"><span className="grid size-10 place-items-center rounded-xl bg-primary font-bold text-white">{index+1}</span><h2 className="mt-8 text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted">A coherent component selected from ${s.card.title}.</p></article>)}</section>`);
  const form=component(componentNames.form,`<section id="contact" className="px-6 py-20"><form onSubmit={event=>event.preventDefault()} className="mx-auto max-w-xl rounded-3xl border border-white/10 bg-card p-7"><h2 className="text-3xl font-black">Tell us about your project</h2><label className="mt-6 block text-sm font-bold">Email<input type="email" required className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-transparent px-3"/></label><label className="mt-4 block text-sm font-bold">Message<textarea required className="mt-2 min-h-28 w-full rounded-xl border border-white/15 bg-transparent p-3"/></label><button className="mt-5 rounded-xl bg-primary px-5 py-3 font-bold text-white">Send request</button></form></section>`);
  const button=component(componentNames.button,`<button type="button" className="rounded-xl bg-primary px-5 py-3 font-bold text-white transition hover:-translate-y-0.5">${s.button.title}</button>`);
  const footer=component(componentNames.footer,`<footer className="border-t border-white/10 px-6 py-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 sm:flex-row"><strong>${safeBrand}</strong><p className="text-sm text-muted">© {new Date().getFullYear()} · Built with Next.js</p></div></footer>`);
  const globals=`@tailwind base;\n@tailwind components;\n@tailwind utilities;\n:root{--background:${config.background};--foreground:#f8fafc;--card:#ffffff0a;--muted:#a1a1aa;--primary:${config.primary};--secondary:${config.secondary}}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--background);color:var(--foreground);font-family:Inter,Arial,sans-serif}.bg-background{background:var(--background)}.text-foreground{color:var(--foreground)}.bg-card{background:var(--card)}.text-muted{color:var(--muted)}.bg-primary{background:var(--primary)}.text-primary{color:var(--primary)}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition-duration:.001ms!important}}\n`;
  const pkg={private:true,scripts:{dev:'next dev',build:'next build',start:'next start'},dependencies:{next:'15.5.9',react:'19.2.1','react-dom':'19.2.1','lucide-react':'^0.475.0','framer-motion':'^12.39.0'},devDependencies:{typescript:'^5.0.0','@types/node':'^20','@types/react':'^19','@types/react-dom':'^19',tailwindcss:'^3.4.1',postcss:'^8',autoprefixer:'^10'}};
  return {'package.json':JSON.stringify(pkg,null,2),'app/layout.tsx':`import './globals.css';\nexport const metadata={title:'${config.projectName}',description:'${config.description}'};\nexport default function Layout({children}:{children:React.ReactNode}){return <html lang="es"><body>{children}</body></html>}\n`,'app/page.tsx':page,'app/globals.css':globals,'components/site-header.tsx':header,'components/site-sidebar.tsx':sidebar,'components/hero-section.tsx':hero,'components/feature-cards.tsx':cards,'components/lead-form.tsx':form,'components/primary-button.tsx':button,'components/site-footer.tsx':footer,'tailwind.config.ts':`import type { Config } from 'tailwindcss';\nexport default {content:['./app/**/*.{ts,tsx}','./components/**/*.{ts,tsx}'],theme:{extend:{}},plugins:[]} satisfies Config;\n`,'postcss.config.mjs':`export default {plugins:{tailwindcss:{},autoprefixer:{}}};\n`,'tsconfig.json':JSON.stringify({compilerOptions:{target:'ES2017',lib:['dom','dom.iterable','esnext'],strict:true,noEmit:true,module:'esnext',moduleResolution:'bundler',jsx:'preserve',paths:{'@/*':['./*']}},include:['next-env.d.ts','**/*.ts','**/*.tsx']},null,2),'next-env.d.ts':`/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n`,'PROMPT.md':config.masterPrompt,'README.md':`# ${config.projectName}\n\nGenerated by Prompt Studio Component Composer.\n\n## Selected components\n\n${chosen}\n\n## Run\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`};
}
export async function POST(request:Request){const status=await getServerSubscriptionStatus();if(!hasDownloadPlan(status))return NextResponse.json({error:'Se requiere una suscripción Premium.'},{status:403});let raw:unknown;try{raw=await request.json()}catch{return NextResponse.json({error:'JSON inválido.'},{status:400})}const config=parse(raw);if(!config)return NextResponse.json({error:'Configuración incompleta.'},{status:400});const project=slug(config.projectName),entries=Object.entries(files(config)).map(([name,value])=>({name:`${project}/${name}`,data:Buffer.from(value,'utf8')}));const zip=createZipArchive(entries);return new NextResponse(new Uint8Array(zip),{headers:{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="${project}.zip"`,'Cache-Control':'private, no-store'}})}
