import type { Metadata } from 'next';
import Link from 'next/link';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import { CrowdfundingCalculatorCheckout } from '@/components/CrowdfundingCalculatorCheckout';
import { CrowdfundingProgress } from '@/components/CrowdfundingProgress';
import type { ReactNode } from 'react';
import { ArrowRight, Bot, CheckCircle2, Code2, Coins, Globe2, ImageIcon, Rocket, Sparkles, Target, Video, WandSparkles, Zap } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { FOUNDER_REWARD_TIERS, getFounderRewardTier } from '@/lib/founder-credit-tiers';
import { InterestPageView } from '@/components/analytics/interest-page-view';

export const metadata: Metadata = {
  title: 'Founder Credits | Prompt Studio',
  description: 'Apoya el crecimiento de Prompt Studio y recibe Founder Credits para crear texto, imágenes, video, sitios web y más con IA.',
};

const tools: Array<[LucideIcon, string, string]> = [
  [Bot, 'Text generation', 'Crea y transforma contenido con IA.'],
  [ImageIcon, 'Image generation', 'Genera imágenes desde 1K hasta 4K.'],
  [Video, 'Video generation', 'Crea clips de IA con opciones de calidad y velocidad.'],
  [Globe2, 'Website generation', 'Genera sitios desde una idea o prompt.'],
  [WandSparkles, 'AI website editing', 'Edita secciones o rediseña páginas con IA.'],
  [Sparkles, 'Prompt optimizer', 'Mejora prompts antes de gastar en una generación.'],
  [Code2, 'Code auditor', 'Analiza código, proyectos y riesgos técnicos.'],
];

const goals = [
  ['$25K', 'Fund', 'Créditos de APIs de IA, infraestructura y lanzamiento.'],
  ['$35K', 'Accelerate', 'Más capacidad de desarrollo y mejoras de producto.'],
  ['$50K', 'Scale', 'Escalado de generación, rendimiento y experiencia.'],
  ['$75K', 'Expand', 'Más herramientas, modelos y flujos para creadores.'],
  ['$100K', 'Build bigger', 'Acelerar la visión completa de Prompt Studio.'],
];

export default async function FounderCreditsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const es = locale === 'es';
  const tr = (en: string, spanish: string) => es ? spanish : en;
  return (
    <div className="min-h-screen overflow-hidden bg-slate-950 text-slate-100"><Header /><InterestPageView page="/crowdfunding" program="founder_credits" /><main className="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:py-20"><div className="pointer-events-none absolute inset-x-0 top-0 -z-0 h-[34rem] bg-[radial-gradient(circle_at_20%_20%,rgba(34,211,238,.16),transparent_32%),radial-gradient(circle_at_80%_10%,rgba(59,130,246,.18),transparent_35%),radial-gradient(circle_at_50%_40%,rgba(37,99,235,.12),transparent_42%)]" />
      <section className="relative z-10 grid items-center gap-10 lg:grid-cols-[1.15fr_.85fr]">
        <div>
          <span className="inline-flex items-center gap-2 rounded-full border border-blue-500/30 bg-blue-500/10 px-3 py-1.5 text-xs font-bold text-blue-300"><Rocket className="size-3.5" /> Prompt Studio · Founder Credits</span>
          <h1 className="mt-5 max-w-4xl bg-gradient-to-r from-white via-blue-400 to-cyan-300 bg-clip-text text-4xl font-black tracking-tight text-transparent sm:text-6xl">{tr('Create with AI. Support us early. Get more creative credits.', 'Crea con IA. Apóyanos desde el inicio y recibe más créditos para crear.')}</h1>
          <p className="mt-5 max-w-2xl text-lg opacity-75">{tr('Prompt Studio brings images, video, websites, text and AI tools into one creative platform. Choose a Founder contribution now and use the corresponding Founder Credits after the campaign ends, even if the campaign does not reach 100% of its funding goal.', 'Prompt Studio reúne imágenes, video, sitios web, texto y herramientas de IA en una sola plataforma. Elige un aporte Founder ahora y usa los Founder Credits correspondientes cuando termine la campaña, aunque la campaña no alcance el 100% de la meta.')}</p>
          <div className="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href="#calculator" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white shadow-lg shadow-blue-500/20 transition hover:bg-blue-500">{tr('Choose Founder Credits', 'Elegir Founder Credits')}<ArrowRight className="size-4" /></a><a href="#how-it-works" className="rounded-xl border border-blue-400/30 px-5 py-3 font-semibold text-blue-100 transition hover:bg-blue-500/10">{tr('How it works', 'Cómo funciona')}</a></div>
          <p className="mt-4 text-sm opacity-60">{tr('Funding goal: $25,000 USD · Non-equity campaign · Founder Credits are available after the campaign ends even if the goal is not fully reached.', 'Meta de crowdfunding: $25,000 USD · Campaña no-equity · Los Founder Credits se habilitan al finalizar la campaña aunque no se alcance el 100% de la meta.')}</p>
          <CrowdfundingProgress />
        </div>
        <div className="relative overflow-hidden rounded-[2rem] border border-blue-500/20 bg-card/70 p-6 shadow-[0_30px_100px_rgba(37,99,235,.16)] backdrop-blur-xl sm:p-8"><div className="absolute -right-16 -top-16 size-48 rounded-full bg-blue-500/15 blur-3xl" /><div className="relative"><div className="mb-5 flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-gradient-to-br from-blue-700 via-blue-500 to-cyan-400 text-white shadow-lg"><Coins className="size-5" /></span><span className="rounded-full border border-cyan-400/25 bg-cyan-400/10 px-3 py-1 text-[11px] font-bold text-cyan-300">+10% BONUS</span></div><p className="text-sm font-medium opacity-60">{tr('Founder example', 'Ejemplo Founder')}</p><div className="mt-2 text-5xl font-bold">4,400</div><p className="mt-1">{tr('Founder Credits with a $50 contribution', 'Founder Credits con un aporte de $50')}</p><div className="my-6 h-px bg-border" /><div className="grid grid-cols-2 gap-4 text-sm"><div><div className="opacity-60">Base</div><strong>4,000</strong></div><div><div className="opacity-60">Bonus</div><strong>+10%</strong></div><div><div className="opacity-60">Quality 1K images</div><strong>{tr('up to 141', 'hasta 141')}</strong></div><div><div className="opacity-60">Advanced websites</div><strong>{tr('up to 88', 'hasta 88')}</strong></div></div><p className="mt-6 text-xs opacity-60">{tr('Examples are category maximums using current prices; they do not represent a fixed generation package.', 'Los ejemplos son máximos por categoría usando precios actuales; no representan un paquete fijo de generaciones.')}</p></div></div>
      </section>

      <section className="mt-20"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-wider opacity-60">{tr('One balance, multiple tools', 'Un saldo, múltiples herramientas')}</p><h2 className="mt-2 text-3xl font-bold">{tr('Create more than prompts', 'Crea más que prompts')}</h2><p className="mt-3 opacity-70">{tr('Prompt Credits abstract provider costs. Prompt Studio can evolve across models and providers while your balance remains expressed in the same internal credit system.', 'Prompt Credits abstrae el costo de los proveedores. Prompt Studio puede evolucionar entre modelos y proveedores mientras tu saldo sigue expresado en la misma moneda interna.')}</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{tools.map(([Icon, name, description]) => <article key={String(name)} className="group rounded-2xl border border-border/60 bg-card/60 p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-500/40 hover:shadow-lg hover:shadow-blue-500/5"><span className="grid size-10 place-items-center rounded-xl bg-blue-500/10 text-blue-400 transition group-hover:bg-blue-600 group-hover:text-white"><Icon className="size-5" /></span><h3 className="mt-4 font-semibold">{name}</h3><p className="mt-2 text-sm opacity-65">{description}</p></article>)}</div></section>

      <section id="calculator" className="relative z-10 mt-20 scroll-mt-8 rounded-[2rem] border border-blue-500/20 bg-gradient-to-br from-blue-500/[.09] via-card/60 to-cyan-500/[.05] p-3 shadow-xl sm:p-6"><div className="mb-6 flex items-center gap-3 px-2"><span className="grid size-10 place-items-center rounded-xl bg-blue-600 text-white"><Zap className="size-5" /></span><div><p className="text-xs font-bold uppercase tracking-widest text-blue-400">{tr('Founder calculator', 'Calculadora Founder')}</p><h2 className="text-xl font-black">{tr('Choose your creative capacity', 'Elige tu capacidad creativa')}</h2></div></div><CrowdfundingCalculatorCheckout /></section>

      <section id="how-it-works" className="mt-20 scroll-mt-8"><h2 className="text-3xl font-bold">{tr('Founder tiers', 'Tiers Founder')}</h2><p className="mt-3 max-w-3xl opacity-70">{tr('Every $1 contributes 80 base credits. Founder tiers add an increasing bonus of up to 20%, while keeping the same Prompt Credit commercial economy used by paid plans.', 'Cada $1 aporta 80 créditos base. Los tiers Founder añaden un bonus creciente de hasta 20%, manteniendo la misma economía comercial de Prompt Credits usada por los planes.')}</p><div className="mt-7 overflow-x-auto rounded-2xl border border-border/60 bg-card/60 shadow-sm"><table className="min-w-full text-sm"><thead><tr className="border-b"><th className="p-4 text-left">{tr('Contribution', 'Aporte')}</th><th className="p-4 text-right">Base</th><th className="p-4 text-right">Bonus</th><th className="p-4 text-right">Total Founder Credits</th></tr></thead><tbody>{FOUNDER_REWARD_TIERS.map((tier) => { const reward = getFounderRewardTier(tier.pledgeAmountCents)!; return <tr key={tier.pledgeAmountCents} className="border-b last:border-0"><td className="p-4 font-semibold">{'$' + tier.pledgeAmountCents / 100}</td><td className="p-4 text-right">{reward.baseCredits.toLocaleString()}</td><td className="p-4 text-right">{'+' + tier.bonusPercent + '%'}</td><td className="p-4 text-right font-semibold">{reward.totalCredits.toLocaleString()}</td></tr>; })}</tbody></table></div></section>

      <section className="mt-20 grid gap-8 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-wider opacity-60">Premium</p><h2 className="mt-2 text-3xl font-bold">$9/month · 500 Prompt Credits</h2><p className="mt-4 opacity-70">Premium es la referencia inicial de la economía: 500 créditos por un ciclo mensual de $9. Founder Credits usan el mismo valor comercial por crédito, con un bonus limitado por tier. Founder Credits son una recompensa separada vinculada al crowdfunding y permanecen diferenciados en el wallet.</p></div><div className="rounded-2xl border p-6"><h3 className="text-xl font-semibold">{tr('When do I receive Founder Credits?', '¿Cuándo recibo Founder Credits?')}</h3><p className="mt-3 opacity-70">{tr('They are not delivered immediately when you contribute. They become eligible after the campaign ends, once Magzin LLC has received the applicable payment and the backer is verified. Reaching 100% of the campaign goal is not required. The operational target is to enable eligible Founder Credits within 14 days after the campaign ends and the payment is confirmed.', 'No se entregan inmediatamente al aportar. Se vuelven elegibles cuando termina la campaña, Magzin LLC ha recibido el pago aplicable y el backer está verificado. No es necesario alcanzar el 100% de la meta. El objetivo operativo es habilitar los Founder Credits elegibles dentro de los 14 días posteriores al cierre de la campaña y la confirmación del pago.')}</p></div></section>

      <section className="mt-20"><p className="text-sm font-semibold uppercase tracking-wider opacity-60">{tr('Campaign roadmap', 'Roadmap de campaña')}</p><h2 className="mt-2 text-3xl font-bold">{tr('From $25K to $100K', 'De $25K a $100K')}</h2><div className="mt-8 grid gap-3 md:grid-cols-5">{goals.map(([amount, title, description], index) => <article key={amount} className="relative overflow-hidden rounded-2xl border border-border/60 bg-card/60 p-5 shadow-sm"><div className="absolute right-3 top-3 text-5xl font-black text-blue-500/[.07]">{index + 1}</div><div className="mb-4 grid size-9 place-items-center rounded-xl bg-blue-500/10 text-blue-400"><Target className="size-4" /></div><div className="text-2xl font-black">{amount}</div><h3 className="mt-2 font-semibold">{title}</h3><p className="mt-2 text-sm opacity-65">{description}</p></article>)}</div><p className="mt-4 text-sm opacity-60">{tr('Stretch goals expand the product and execution capacity; they do not automatically add credits to Founder rewards.', 'Los stretch goals amplían el producto y la capacidad de ejecución; no añaden automáticamente créditos a las recompensas Founder.')}</p></section>

      <section className="mt-20 grid gap-8 rounded-3xl border border-blue-500/20 bg-gradient-to-br from-card via-card to-blue-500/[.06] p-6 shadow-lg sm:p-10 lg:grid-cols-2"><div><h2 className="text-3xl font-bold">{tr('How will the support be used?', '¿En qué se utilizará el apoyo?')}</h2><p className="mt-4 opacity-70">{tr('Mainly AI API and model costs, product development, infrastructure, stability and scaling. The campaign goal helps us expand execution capacity, but Founder Credit eligibility does not depend on reaching 100% of that goal.', 'Principalmente en costos de APIs y créditos de IA, desarrollo de producto, infraestructura, estabilidad y escalado. La meta nos ayuda a ampliar la capacidad de ejecución, pero la elegibilidad de los Founder Credits no depende de alcanzar el 100% de esa meta.')}</p></div><div className="space-y-4"><Info title="Proveedor agnóstico">Tu saldo no representa dólares de Gemini, OpenAI u otro proveedor.</Info><Info title="Precio visible">Antes de una generación pagada, Prompt Studio puede mostrar el costo estimado en créditos; el servidor confirma el precio y reserva el saldo.</Info><Info title="Sin promesas de generaciones fijas">Los costos pueden evolucionar con modelos, calidad y economía de proveedores; por eso la recompensa se expresa en créditos.</Info></div></section>

      <section className="mt-20"><h2 className="text-3xl font-bold">{tr('Frequently asked questions', 'Preguntas frecuentes')}</h2><div className="mt-6 grid gap-3 lg:grid-cols-2"><Info title="¿Founder Credits son dinero o inversión?">No. Son créditos internos de Prompt Studio para uso del producto. La campaña planteada es no-equity.</Info><Info title="¿Los créditos están ligados a una API?">No. Prompt Studio puede enrutar generaciones entre proveedores/modelos y mantener Prompt Credits como moneda interna estable para el usuario.</Info><Info title="¿Puedo comprar créditos aparte?">La economía contempla paquetes de una sola compra además de créditos mensuales Premium y Founder Credits.</Info><Info title="¿Todos los usos cuestan lo mismo?">No. Texto, imágenes, video, websites, edición y auditoría tienen costos distintos según el trabajo solicitado. Algunas acciones como el preview simple de componentes pueden ser gratuitas.</Info></div></section>

      <section className="relative mt-20 overflow-hidden rounded-3xl border border-blue-500/30 bg-gradient-to-br from-blue-600/15 via-card to-cyan-500/10 p-8 text-center shadow-xl sm:p-12"><div className="pointer-events-none absolute left-1/2 top-0 h-48 w-96 -translate-x-1/2 rounded-full bg-blue-500/15 blur-3xl" /><div className="relative"><h2 className="text-3xl font-bold">{tr('Build with Prompt Studio', 'Construye con Prompt Studio')}</h2><p className="mx-auto mt-3 max-w-2xl opacity-70">Explora la plataforma ahora y vuelve a esta página para calcular qué capacidad de creación recibirías como Founder.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/" className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white transition hover:bg-blue-500">{tr('Explore Prompt Studio', 'Explorar Prompt Studio')}</Link><a href="#calculator" className="rounded-xl border border-blue-400/30 px-5 py-3 font-semibold text-blue-100 transition hover:bg-blue-500/10">{tr('Calculate credits', 'Calcular créditos')}</a></div></div></section>
    </main><Footer /></div>
  );
}

function Info({ title, children }: { title: string; children: ReactNode }) { return <div className="group rounded-2xl border border-border/60 bg-card/60 p-5 shadow-sm transition hover:border-blue-500/30"><div className="flex items-start gap-3"><span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-blue-500/10 text-blue-400"><CheckCircle2 className="size-4" /></span><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm opacity-65">{children}</p></div></div></div>; }
