import type { Metadata } from 'next';
import Link from 'next/link';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';

export const metadata: Metadata = { title: 'Crowdfunding Terms | Prompt Studio', description: 'Terms governing Prompt Studio crowdfunding contributions and Founder Credits.' };

const sections = [
 ['Nature of the campaign','Naturaleza de la campaña','Prompt Studio crowdfunding is a non-equity support campaign operated by Magzin LLC. A contribution does not purchase shares, ownership, voting rights, profit participation, debt, or any other security.','El crowdfunding de Prompt Studio es una campaña de apoyo no-equity operada por Magzin LLC. Un aporte no compra acciones, propiedad, derechos de voto, participación en utilidades, deuda ni ningún otro valor.'],
 ['Contributions and Stripe','Aportes y Stripe','Contributions are processed by Stripe in USD. The amount, currency and payment status confirmed by Stripe control the payment record. Prompt Studio may reject or refund transactions affected by fraud, chargebacks, sanctions, payment errors or legal restrictions.','Los aportes se procesan mediante Stripe en USD. El monto, moneda y estado de pago confirmados por Stripe controlan el registro del pago. Prompt Studio puede rechazar o reembolsar operaciones afectadas por fraude, contracargos, sanciones, errores de pago o restricciones legales.'],
 ['Founder Credits','Founder Credits','Founder Credits are internal, non-cash Prompt Studio credits intended for eligible product usage. They are not legal tender, a bank balance, stored monetary value, cryptocurrency, investment, security, transferable asset or claim against Magzin LLC. They cannot be redeemed for cash unless required by applicable law.','Founder Credits son créditos internos, no monetarios, de Prompt Studio destinados al uso elegible del producto. No son moneda de curso legal, saldo bancario, valor monetario almacenado, criptomoneda, inversión, valor, activo transferible ni reclamación contra Magzin LLC. No pueden canjearse por efectivo salvo cuando la ley aplicable lo exija.'],
 ['Reward calculation','Cálculo de recompensas','Displayed Founder Credit amounts are calculated under the published campaign tiers. Estimates of images, videos, websites or other generations are illustrative category maximums based on current Prompt Credit prices and are not a promise of a fixed number of generations.','Las cantidades mostradas de Founder Credits se calculan conforme a los tiers publicados de la campaña. Las estimaciones de imágenes, videos, sitios web u otras generaciones son máximos ilustrativos por categoría basados en los precios actuales de Prompt Credits y no constituyen una promesa de un número fijo de generaciones.'],
 ['When credits become available','Cuándo se habilitan los créditos','Payment alone does not grant Founder Credits. Eligibility requires the campaign to be successfully funded, Magzin LLC to receive the applicable campaign funds, and the backer/payment to be verified. The operational target is to enable eligible Founder Credits within 14 days after successful receipt of campaign proceeds.','El pago por sí solo no acredita Founder Credits. La elegibilidad requiere que la campaña sea financiada exitosamente, que Magzin LLC reciba los fondos aplicables de la campaña y que el backer/pago sea verificado. El objetivo operativo es habilitar los Founder Credits elegibles dentro de los 14 días posteriores a la recepción exitosa de los fondos de la campaña.'],
 ['Campaign changes and stretch goals','Cambios de campaña y stretch goals','Roadmap items and stretch goals describe intended product direction, not guaranteed delivery dates or additional Founder Credits. Stretch goals do not automatically increase a backer reward. Product scope, providers, models and implementation may change as the platform evolves.','Los elementos del roadmap y stretch goals describen la dirección prevista del producto, no fechas de entrega garantizadas ni Founder Credits adicionales. Los stretch goals no aumentan automáticamente la recompensa de un backer. El alcance, proveedores, modelos e implementación pueden cambiar conforme evoluciona la plataforma.'],
 ['Refunds and failed campaigns','Reembolsos y campañas no exitosas','Refund eligibility depends on the payment channel, campaign status, applicable Prompt Studio refund rules and mandatory consumer law. If a campaign mechanism collects funds before success, the campaign-specific checkout disclosures govern how unsuccessful funding is handled. Chargebacks or refunded contributions may cancel related Founder Credit eligibility.','La elegibilidad para reembolso depende del canal de pago, estado de la campaña, reglas de reembolso aplicables de Prompt Studio y legislación obligatoria de consumo. Si un mecanismo de campaña cobra fondos antes del éxito, las divulgaciones específicas del checkout regirán el tratamiento de una financiación no exitosa. Los contracargos o aportes reembolsados pueden cancelar la elegibilidad relacionada de Founder Credits.'],
 ['Risks and availability','Riesgos y disponibilidad','Crowdfunding supports ongoing product development and involves execution risk. Features, providers, costs, timelines and availability can change. Prompt Studio does not guarantee that every planned feature, model, integration or stretch goal will be delivered exactly as described.','El crowdfunding apoya desarrollo continuo del producto e implica riesgo de ejecución. Funciones, proveedores, costos, plazos y disponibilidad pueden cambiar. Prompt Studio no garantiza que cada función, modelo, integración o stretch goal planeado se entregue exactamente como se describe.'],
 ['Acceptable use and account','Uso aceptable y cuenta','Founder Credits remain subject to Prompt Studio Terms of Use, acceptable-use rules, account security requirements and product restrictions. Abuse, fraud or prohibited activity may result in suspension, cancellation or other remedies permitted by the Terms and applicable law.','Founder Credits permanecen sujetos a los Términos de Uso de Prompt Studio, reglas de uso aceptable, requisitos de seguridad de cuenta y restricciones del producto. Abuso, fraude o actividad prohibida puede resultar en suspensión, cancelación u otras medidas permitidas por los Términos y la ley aplicable.'],
 ['Privacy','Privacidad','Personal data related to accounts, payments and campaign administration is handled under the Prompt Studio Privacy Policy and applicable law. Stripe processes payment information under its own terms and privacy practices.','Los datos personales relacionados con cuentas, pagos y administración de campaña se tratan conforme a la Política de Privacidad de Prompt Studio y la ley aplicable. Stripe procesa información de pago conforme a sus propios términos y prácticas de privacidad.'],
 ['Operator and contact','Operador y contacto','Prompt Studio is operated by Magzin LLC. Questions about the campaign, payments or Founder Credits may be sent to help@prompstudio.com. These Crowdfunding Terms supplement the general Prompt Studio Terms, Privacy Policy and Refund Policy.','Prompt Studio es operado por Magzin LLC. Las preguntas sobre la campaña, pagos o Founder Credits pueden enviarse a help@prompstudio.com. Estos Términos de Crowdfunding complementan los Términos generales de Prompt Studio, la Política de Privacidad y la Política de Reembolsos.'],
] as const;

export default async function CrowdfundingTermsPage({params}:{params:Promise<{locale:string}>}) {
 const {locale}=await params; const es=locale==='es';
 return <div className="flex min-h-screen flex-col bg-background"><Header/><main className="flex-1 py-12 md:py-20"><div className="container max-w-4xl px-4 md:px-6">
  <div className="mb-10 border-b border-border/60 pb-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-cyan-500">Prompt Studio · Crowdfunding</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{es?'Términos de Crowdfunding':'Crowdfunding Terms'}</h1><p className="mt-4 text-muted-foreground">{es?'Última actualización: octubre de 2026':'Last updated: October 2026'}</p></div>
  <div className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">{es?'Resumen importante: ':'Important summary: '}</strong>{es?'La campaña es no-equity. Founder Credits no son dinero ni una inversión y no se acreditan únicamente por completar un pago. Lee estas condiciones antes de aportar.':'The campaign is non-equity. Founder Credits are not money or an investment and are not granted merely by completing a payment. Read these terms before contributing.'}</div>
  <div className="mt-10 space-y-10">{sections.map(([enTitle,esTitle,enBody,esBody],i)=><section key={enTitle}><h2 className="text-2xl font-bold">{i+1}. {es?esTitle:enTitle}</h2><p className="mt-3 leading-7 text-muted-foreground">{es?esBody:enBody}</p></section>)}</div>
  <div className="mt-12 flex flex-wrap gap-3 border-t pt-8"><Link href="/founder" className="rounded-xl bg-foreground px-5 py-3 font-semibold text-background">{es?'Volver a Crowdfunding':'Back to Crowdfunding'}</Link><Link href="/terms" className="rounded-xl border px-5 py-3 font-semibold">{es?'Términos generales':'General Terms'}</Link><Link href="/refunds" className="rounded-xl border px-5 py-3 font-semibold">{es?'Reembolsos':'Refunds'}</Link></div>
 </div></main><Footer/></div>;
}