import { auth, clerkClient } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';
import mongoose from 'mongoose';
import connectToDatabase from '@/lib/mongoose';
import { brandPreferenceKey, evaluationPairKey, isHumanEvaluationReason, preferenceScores } from '@/lib/human-preferences';
import { rateLimit, tooManyRequests } from '@/lib/rate-limit';
import AIGenerationJob, { type AIJobKind } from '@/models/AIGenerationJob';
import CreativeProject from '@/models/CreativeProject';
import HumanEvaluation from '@/models/HumanEvaluation';

const headers = { 'Cache-Control': 'private, no-store' };
function blind(value:unknown):unknown{if(typeof value==='string'&&/^(openai|google|anthropic|deepseek|runway|veo|kling|luma|pika|hailuo|sora|fal|replicate|gpt|gemini|claude)([/:\s-].*)?$/i.test(value))return'[oculto]';if(Array.isArray(value))return value.map(blind);if(value&&typeof value==='object'){const output:Record<string,unknown>={};for(const[key,item]of Object.entries(value))if(!/provider|model|engine|vendor/i.test(key))output[key]=blind(item);return output}return value}
const option=(job:any)=>({id:String(job._id),kind:job.kind,result:blind(job.result),resolution:job.outputResolution??null,quality:job.outputQuality??null,completedAt:job.completedAt});

async function projectContext(projectId:string,userId:string){if(!projectId)return{ownerId:userId,brandKey:null};if(!mongoose.isValidObjectId(projectId))return null;const user=await(await clerkClient()).users.getUser(userId),email=user.primaryEmailAddress?.emailAddress?.toLowerCase()||'',project=await CreativeProject.findOne({_id:projectId,$or:[{userId},{'collaborators.userId':userId},{'collaborators.email':email}]}).select('userId brand').lean();return project?{ownerId:project.userId,brandKey:brandPreferenceKey(project.brand)}:null}

export async function GET(request:Request){const{userId}=await auth();if(!userId)return NextResponse.json({error:'No autorizado.'},{status:401,headers});const url=new URL(request.url),kind=(['image','video','project'].includes(url.searchParams.get('kind')||'')?url.searchParams.get('kind'):'image')as AIJobKind,projectId=url.searchParams.get('projectId')?.trim()||'';await connectToDatabase();const context=await projectContext(projectId,userId);if(!context)return NextResponse.json({error:'Proyecto no disponible.'},{status:403,headers});let evaluation=await HumanEvaluation.findOne({userId,kind,projectId:projectId||null,status:'pending',expiresAt:{$gt:new Date()}}).sort({createdAt:-1});if(!evaluation){const jobs=await AIGenerationJob.find({userId:context.ownerId,kind,status:'completed',...(projectId?{projectId}:{})}).sort({completedAt:-1}).limit(100).select('provider kind result outputResolution outputQuality completedAt').lean();outer:for(let a=0;a<jobs.length;a++)for(let b=a+1;b<jobs.length;b++){if(jobs[a]!.provider===jobs[b]!.provider)continue;const pairKey=evaluationPairKey(String(jobs[a]!._id),String(jobs[b]!._id));if(await HumanEvaluation.exists({userId,pairKey}))continue;const reversed=crypto.getRandomValues(new Uint8Array(1))[0]!%2===1;evaluation=await HumanEvaluation.create({userId,projectId:projectId||null,brandKey:context.brandKey,kind,pairKey,optionAJobId:reversed?jobs[b]!._id:jobs[a]!._id,optionBJobId:reversed?jobs[a]!._id:jobs[b]!._id,status:'pending',expiresAt:new Date(Date.now()+24*60*60*1000)});break outer}}
  const votes=await HumanEvaluation.find({userId,kind,status:'completed'}).select('winnerProvider loserProvider brandKey').lean(),preferences=[...preferenceScores(votes.filter(v=>v.winnerProvider&&v.loserProvider).map(v=>({winnerProvider:v.winnerProvider!,loserProvider:v.loserProvider!,brandKey:v.brandKey??null})),context.brandKey)].map(([provider,value])=>({provider,...value})).sort((a,b)=>b.boost-a.boost);
  if(!evaluation)return NextResponse.json({evaluation:null,preferences,completed:votes.length},{headers});const jobs=await AIGenerationJob.find({_id:{$in:[evaluation.optionAJobId,evaluation.optionBJobId]},userId:context.ownerId,status:'completed'}).lean(),byId=new Map(jobs.map(job=>[String(job._id),job])),a=byId.get(String(evaluation.optionAJobId)),b=byId.get(String(evaluation.optionBJobId));if(!a||!b)return NextResponse.json({evaluation:null,preferences,completed:votes.length},{headers});return NextResponse.json({evaluation:{id:String(evaluation._id),kind,optionA:option(a),optionB:option(b)},preferences,completed:votes.length},{headers})}

export async function POST(request:Request){const{userId}=await auth();if(!userId)return NextResponse.json({error:'No autorizado.'},{status:401,headers});const quota=await rateLimit({key:`human-evaluation:${userId}`,limit:40,windowMs:60_000});if(!quota.ok)return tooManyRequests(quota);const body=await request.json().catch(()=>null)as Record<string,unknown>|null,id=typeof body?.id==='string'?body.id:'',winner=body?.winner,reason=body?.reason,note=typeof body?.note==='string'?body.note.trim().slice(0,1000):'';if(!mongoose.isValidObjectId(id)||(winner!=='A'&&winner!=='B')||!isHumanEvaluationReason(reason))return NextResponse.json({error:'Evaluación inválida.'},{status:400,headers});await connectToDatabase();const evaluation=await HumanEvaluation.findOne({_id:id,userId,status:'pending',expiresAt:{$gt:new Date()}});if(!evaluation)return NextResponse.json({error:'La comparación expiró o ya fue respondida.'},{status:409,headers});const jobs=await AIGenerationJob.find({_id:{$in:[evaluation.optionAJobId,evaluation.optionBJobId]},status:'completed'}).select('provider').lean(),byId=new Map(jobs.map(job=>[String(job._id),job.provider])),winnerId=winner==='A'?evaluation.optionAJobId:evaluation.optionBJobId,loserId=winner==='A'?evaluation.optionBJobId:evaluation.optionAJobId,winnerProvider=byId.get(String(winnerId)),loserProvider=byId.get(String(loserId));if(!winnerProvider||!loserProvider)return NextResponse.json({error:'Los resultados ya no están disponibles.'},{status:409,headers});evaluation.status='completed';evaluation.winner=winner;evaluation.winnerProvider=winnerProvider;evaluation.loserProvider=loserProvider;evaluation.reason=reason;evaluation.note=note;evaluation.completedAt=new Date();await evaluation.save();return NextResponse.json({ok:true},{status:201,headers})}
