'use client';
import { useCallback, useEffect, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Textarea } from '@/components/ui/textarea';
import { FlaskConical, Gauge, Heart, Play, RefreshCw } from 'lucide-react';
type Run={key:string;promptLabel:'A'|'B';provider:string;jobId:string;status:string;progress:number;resultUrl:string|null;metrics:{durationMs:number|null;costUsd:number;fidelity:number|null;quality:number|null}|null};
type Experiment={id:string;title:string;promptA:string;promptB:string;preferredRunKey:string|null;createdAt:string;runs:Run[]};
export function PromptLabClient(){
 const[title,setTitle]=useState(''),[promptA,setPromptA]=useState(''),[promptB,setPromptB]=useState(''),[experiment,setExperiment]=useState<Experiment|null>(null),[history,setHistory]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const loadHistory=useCallback(async()=>{const r=await fetch('/api/prompt-experiments',{cache:'no-store'});if(r.ok)setHistory((await r.json()).experiments)},[]);
 const loadExperiment=useCallback(async(id:string)=>{const r=await fetch(`/api/prompt-experiments/${id}`,{cache:'no-store'});if(r.ok)setExperiment((await r.json()).experiment)},[]);
 useEffect(()=>{void loadHistory()},[loadHistory]);
 useEffect(()=>{if(!experiment||experiment.runs.every(run=>['completed','failed'].includes(run.status)))return;const timer=window.setInterval(()=>void loadExperiment(experiment.id),4000);return()=>window.clearInterval(timer)},[experiment,loadExperiment]);
 const create=async()=>{setBusy(true);setError('');const r=await fetch('/api/prompt-experiments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,promptA,promptB})});const data=await r.json().catch(()=>({}));if(r.ok){await loadExperiment(data.id);await loadHistory()}else setError(data.error||'No se pudo crear el experimento.');setBusy(false)};
 const vote=async(key:string)=>{if(!experiment)return;const r=await fetch(`/api/prompt-experiments/${experiment.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferredRunKey:key})});if(r.ok)setExperiment({...experiment,preferredRunKey:key})};
 return <div className="mx-auto w-full max-w-7xl space-y-6"><div><Badge variant="secondary" className="mb-3 gap-1"><FlaskConical className="size-3"/>Laboratorio A/B</Badge><h1 className="text-3xl font-bold">Compara prompts y proveedores</h1><p className="mt-2 text-muted-foreground">Ejecuta Prompt A y Prompt B con Gemini y OpenAI bajo la misma matriz. Costo total estimado: 4 créditos.</p></div>
 <Card><CardContent className="grid gap-4 p-5 lg:grid-cols-2"><div className="lg:col-span-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nombre del experimento" className="h-10 w-full rounded-md border bg-background px-3" maxLength={160}/></div><label className="space-y-2"><span className="font-semibold">Prompt A</span><Textarea value={promptA} onChange={e=>setPromptA(e.target.value)} className="min-h-44" maxLength={20000}/></label><label className="space-y-2"><span className="font-semibold">Prompt B</span><Textarea value={promptB} onChange={e=>setPromptB(e.target.value)} className="min-h-44" maxLength={20000}/></label><div className="flex flex-wrap items-center gap-3 lg:col-span-2"><Button onClick={create} disabled={busy||promptA.trim().length<10||promptB.trim().length<10||promptA===promptB}><Play className="mr-2 size-4"/>{busy?'Creando…':'Ejecutar 4 pruebas'}</Button>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</div></CardContent></Card>
 {experiment&&<section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">{experiment.title}</h2><Button variant="outline" size="sm" onClick={()=>loadExperiment(experiment.id)}><RefreshCw className="mr-2 size-4"/>Actualizar</Button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{experiment.runs.map(run=><Card key={run.key} className={experiment.preferredRunKey===run.key?'border-primary ring-1 ring-primary':''}><CardHeader><div className="flex justify-between"><CardTitle>Prompt {run.promptLabel}</CardTitle><Badge variant="outline">{run.provider==='google'?'Gemini':'OpenAI'}</Badge></div></CardHeader><CardContent className="space-y-4">{run.resultUrl?<img src={run.resultUrl} alt={`Resultado ${run.key}`} className="aspect-square w-full rounded-lg border object-cover"/>:<div className="flex aspect-square items-center justify-center rounded-lg border bg-muted text-sm text-muted-foreground">{run.status}</div>}<Progress value={run.progress}/><div className="grid grid-cols-2 gap-2 text-xs"><Metric label="Velocidad" value={run.metrics?.durationMs!=null?`${(run.metrics.durationMs/1000).toFixed(1)}s`:'—'}/><Metric label="Costo" value={run.metrics?`$${run.metrics.costUsd.toFixed(2)}`:'—'}/><Metric label="Fidelidad" value={run.metrics?.fidelity!=null?`${run.metrics.fidelity}/100`:'Pendiente'}/><Metric label="Calidad" value={run.metrics?.quality!=null?`${run.metrics.quality}/100`:'Pendiente'}/></div><Button variant={experiment.preferredRunKey===run.key?'default':'outline'} className="w-full" onClick={()=>vote(run.key)} disabled={run.status!=='completed'}><Heart className="mr-2 size-4"/>{experiment.preferredRunKey===run.key?'Preferido':'Elegir resultado'}</Button></CardContent></Card>)}</div><p className="flex items-start gap-2 text-xs text-muted-foreground"><Gauge className="mt-0.5 size-4 shrink-0"/>Fidelidad y calidad aparecen cuando el worker devuelve una evaluación estructurada. No se inventan puntuaciones sin evidencia.</p></section>}
 {history.length>0&&<Card><CardHeader><CardTitle>Experimentos recientes</CardTitle></CardHeader><CardContent className="space-y-2">{history.map(item=><button key={item._id} onClick={()=>loadExperiment(item._id)} className="flex w-full items-center justify-between rounded-lg border p-3 text-left hover:bg-muted"><span>{item.title}</span><span className="text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</span></button>)}</CardContent></Card>}</div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-md bg-muted p-2"><span className="block text-muted-foreground">{label}</span><strong>{value}</strong></div>}
