'use client';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { useDailyCopyLimit } from '@/hooks/use-daily-copy-limit';
import { useMembershipAccess } from '@/hooks/use-membership-access';
import { copyToClipboard } from '@/lib/copy-to-clipboard';
import { Check,Copy,Download,PanelsTopLeft } from 'lucide-react';
import { useMemo,useState } from 'react';

type Platform='react'|'nextjs'|'vue'|'svelte'|'html'|'tailwind'|'shadcn'|'webflow'|'framer'|'v0'|'bolt'|'lovable';
type PlatformRule={label:string;format:string;replace:string;requirements:string[]};
const rules:Record<Platform,PlatformRule>={
  react:{label:'React',format:'React component files written in TypeScript and CSS modules or the requested styling system.',replace:'Replace framework-specific routing, image and server APIs with portable React equivalents.',requirements:['Use functional components and typed props','Separate reusable UI, state and sample data','Include loading, error and empty states','Provide Vite-compatible setup instructions']},
  nextjs:{label:'Next.js',format:'Next.js App Router files using React and TypeScript.',replace:'Use Next.js primitives and remove assumptions from other application frameworks.',requirements:['Prefer Server Components; add use client only when interaction requires it','Use next/image, next/link and next/font where appropriate','Include route-level metadata and semantic landmarks','Document App Router file locations and dependencies']},
  vue:{label:'Vue',format:'Vue 3 Single File Components with TypeScript.',replace:'Translate React components, hooks and JSX into Vue Composition API, refs, computed values and events.',requirements:['Use <script setup lang="ts">','Define typed props and emits','Keep styles scoped unless tokens must be global','Include accessible interactive and responsive states']},
  svelte:{label:'Svelte',format:'Svelte components with TypeScript.',replace:'Translate React or Vue state patterns into idiomatic Svelte state, derived values and event handling.',requirements:['Use semantic Svelte component markup','Expose typed component properties','Avoid React-only packages and APIs','Include reduced-motion and keyboard behavior']},
  html:{label:'HTML/CSS/JS',format:'Independent index.html, styles.css and script.js files.',replace:'Remove all framework, JSX, TypeScript-only and build-time dependencies.',requirements:['Use semantic HTML and native browser APIs','Use progressive enhancement','Keep JavaScript modular and dependency-free','Make the result runnable by opening index.html']},
  tailwind:{label:'Tailwind',format:'Framework-compatible markup styled primarily with Tailwind CSS utilities.',replace:'Replace custom visual CSS with maintainable Tailwind utilities while preserving necessary keyframes and CSS variables.',requirements:['Use a consistent utility and responsive breakpoint strategy','Extract repeated class patterns into components','Declare custom tokens in the Tailwind theme','Do not use arbitrary values when a named token is appropriate']},
  shadcn:{label:'shadcn/ui',format:'React and TypeScript components compatible with the shadcn Registry.',replace:'Map generic controls to shadcn/ui primitives and remove incompatible UI libraries.',requirements:['List every required shadcn component and install command','Use cn for conditional classes','Preserve Radix accessibility behavior','Return a valid registry-item JSON example']},
  webflow:{label:'Webflow',format:'A Webflow implementation plan with element hierarchy, reusable classes, variables and interactions.',replace:'Do not return React, Vue or framework code. Translate component logic to Webflow native elements, CMS, forms and interactions.',requirements:['Provide Navigator hierarchy and class naming','Define Variables for colors, type, spacing and radii','Describe breakpoints and interactions step by step','Identify any unavoidable custom code separately']},
  framer:{label:'Framer',format:'A Framer-ready component and visual construction guide.',replace:'Translate framework-specific UI into Framer layers, components, variants and property controls.',requirements:['Define desktop, tablet and phone breakpoints','Expose text, color, boolean and enum property controls','Use Framer Motion only for meaningful interaction','Describe component variants and responsive constraints']},
  v0:{label:'v0',format:'A concise v0 generation prompt targeting Next.js, Tailwind CSS and shadcn/ui.',replace:'Resolve the source prompt to the v0 stack; remove conflicting frameworks and redundant prose.',requirements:['State the exact component and visual outcome first','Specify interactions, responsive states and sample content','Request complete usable code rather than a mockup','Mention required shadcn components and icons']},
  bolt:{label:'Bolt',format:'A repository-level build instruction for Bolt.',replace:'Resolve all framework conflicts and select one installable stack before generating files.',requirements:['Specify package installation and scripts','Request a complete working file tree','Require real interactions and state handling','Finish with build verification and fixes for runtime errors']},
  lovable:{label:'Lovable',format:'A Lovable-ready product instruction using React, TypeScript and Tailwind CSS.',replace:'Translate unsupported libraries into the standard Lovable frontend stack; use Supabase only if persistence is actually required.',requirements:['Describe the user flow before visual details','Define reusable components and responsive behavior','Request real forms, validation and feedback states','Do not add authentication or a database unless required']},
};
const platforms=Object.keys(rules)as Platform[];
function generate(basePrompt:string,name:string,type:string,platform:Platform){const rule=rules[platform];return `Create “${name}”, a ${type} component, specifically for ${rule.label}.\n\nDELIVERY FORMAT\n${rule.format}\n\nPLATFORM ADAPTATION\n${rule.replace}\n${rule.requirements.map(value=>`- ${value}.`).join('\n')}\n\nSOURCE REQUIREMENTS\n${basePrompt}\n\nFINAL QUALITY RULES\n- Preserve the original content, visual hierarchy, brand tokens and functional intent.\n- When a source requirement conflicts with ${rule.label}, follow the platform adaptation above and document the substitution.\n- Implement responsive behavior, semantic structure, keyboard access, visible focus, WCAG AA contrast and reduced-motion fallback.\n- Do not invent APIs, packages, testimonials or integrations.\n- Return the complete implementation in the delivery format, followed by setup and verification steps.`}

export default function PlatformPromptGenerator({basePrompt,name,type}:{basePrompt:string;name:string;type:string}){const{copyWithDailyLimit}=useDailyCopyLimit(),{runWithAccess}=useMembershipAccess();const[platform,setPlatform]=useState<Platform>('nextjs'),[copied,setCopied]=useState(false);const prompt=useMemo(()=>generate(basePrompt,name,type,platform),[basePrompt,name,type,platform]);const all=useMemo(()=>Object.fromEntries(platforms.map(key=>[key,{platform:rules[key].label,prompt:generate(basePrompt,name,type,key)}])),[basePrompt,name,type]);const copy=async()=>{const result=await copyWithDailyLimit(()=>copyToClipboard(prompt));if(result==='copied'){setCopied(true);window.setTimeout(()=>setCopied(false),1600)}};const download=()=>runWithAccess('Premium',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({component:name,type,versions:all},null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'component'}-platform-prompts.json`;anchor.click();URL.revokeObjectURL(url)});return <div className="rounded-xl border bg-muted/30 p-3"><div className="flex items-center justify-between"><p className="text-xs font-black">Prompts por plataforma</p><Badge variant="outline">12 versiones</Badge></div><Select value={platform} onValueChange={value=>setPlatform(value as Platform)}><SelectTrigger className="mt-3 h-9 text-xs"><SelectValue/></SelectTrigger><SelectContent>{platforms.map(key=><SelectItem key={key} value={key}>{rules[key].label}</SelectItem>)}</SelectContent></Select><div className="mt-2 grid grid-cols-4 gap-1">{platforms.map(key=><button key={key} type="button" onClick={()=>setPlatform(key)} className={`truncate rounded-md border px-1 py-1.5 text-[8px] font-bold ${platform===key?'border-violet-600 bg-violet-600 text-white':''}`}>{rules[key].label}</button>)}</div><pre className="mt-3 max-h-40 overflow-auto whitespace-pre-wrap rounded-lg bg-zinc-950 p-3 text-[9px] leading-4 text-zinc-200">{prompt}</pre><div className="mt-2 grid grid-cols-2 gap-2"><Button size="sm" variant="outline" onClick={()=>void copy()}>{copied?<Check className="mr-1 size-3.5"/>:<Copy className="mr-1 size-3.5"/>}{copied?'Copiado':'Copiar versión'}</Button><Button size="sm" className="bg-violet-600 hover:bg-violet-700" onClick={download}><Download className="mr-1 size-3.5"/>Descargar todas</Button></div><p className="mt-2 flex items-center gap-1 text-[9px] text-muted-foreground"><PanelsTopLeft className="size-3"/>La descarga de las 12 versiones requiere Premium.</p></div>}
