import {createHash} from 'node:crypto';
export const REFACTORY_BUNDLE_SCHEMA_VERSION=1 as const;
export type RefactoryProvenance={generationJobId?:string;provider?:string;modelId?:string;promptVersionId?:string;promptHash?:string;generatedAt?:string};
export type RefactoryManifest={schemaVersion:1;bundleId:string;slug:string;projectKind:'html';entrypoint:'index.html';assets:Array<{path:string;sha256:string;bytes:number;mediaType:string}>;provenance:RefactoryProvenance};
export type RefactoryBundleInput={slug:string;files:Record<string,string>;provenance?:RefactoryProvenance};
const safe=(p:string)=>/^[a-zA-Z0-9][a-zA-Z0-9._/-]*$/.test(p)&&!p.includes('..')&&!p.startsWith('/');
export const sha256=(s:string)=>createHash('sha256').update(s).digest('hex');
export function buildRefactoryManifest(input:RefactoryBundleInput):RefactoryManifest{const paths=Object.keys(input.files).sort();if(!paths.includes('index.html'))throw new Error('ENTRYPOINT_MISSING');for(const p of paths)if(!safe(p))throw new Error('UNSAFE_ASSET_PATH');const assets=paths.map(path=>{const value=input.files[path]!;return {path,sha256:sha256(value),bytes:Buffer.byteLength(value),mediaType:path.endsWith('.html')?'text/html':path.endsWith('.css')?'text/css':path.endsWith('.js')?'text/javascript':'text/plain'}});const content=JSON.stringify({schemaVersion:1,slug:input.slug,assets:assets.map(a=>[a.path,a.sha256]),provenance:input.provenance??{}});return {schemaVersion:1,bundleId:`sha256:${sha256(content)}`,slug:input.slug,projectKind:'html',entrypoint:'index.html',assets,provenance:input.provenance??{}}}
export function validateRefactoryBundle(manifest:RefactoryManifest,files:Record<string,string>){const errors:string[]=[];if(manifest.schemaVersion!==1)errors.push('SCHEMA_UNSUPPORTED');if(manifest.entrypoint!=='index.html'||!files['index.html'])errors.push('ENTRYPOINT_MISSING');for(const asset of manifest.assets){if(!safe(asset.path))errors.push(`UNSAFE_PATH:${asset.path}`);const value=files[asset.path];if(value===undefined)errors.push(`ASSET_MISSING:${asset.path}`);else if(sha256(value)!==asset.sha256)errors.push(`HASH_MISMATCH:${asset.path}`)}const rebuilt=errors.length?null:buildRefactoryManifest({slug:manifest.slug,files,provenance:manifest.provenance});if(rebuilt&&rebuilt.bundleId!==manifest.bundleId)errors.push('BUNDLE_ID_MISMATCH');return {valid:errors.length===0,errors}}
export function sandboxPolicy(){return {sandbox:'allow-scripts',allow:"'none'",referrerPolicy:'no-referrer',contentSecurityPolicy:"default-src 'none'; img-src data: https:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"} as const}
