'use client';
import { useEffect,useState } from 'react';import Link from 'next/link';
import { ArrowRight,BrainCircuit,Component,Flame,ImageIcon,LayoutTemplate,Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';import { Button } from '@/components/ui/button';import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
type Recommendation={id:string;kind:'prompt'|'model'|'component'|'template';title:string;description:string;href:string;imageUrl?:string|null;score:number;reasons:string[]};
type Payload={continueItem:{title:string;description:string;href:string;reason:string}|null;nextStep:{title:string;description:string;href:string;reason:string};recommendations:Recommendation[];explanation:{signals:Record<string,number>;method:string}};
const labels={prompt:'Prompt relacionado',model:'Modelo recomendado',component:'Componente compatible',template:'Plantilla para ti'};
const icons={prompt:ImageIcon,model:BrainCircuit,component:Component,template:LayoutTemplate};
export function PersonalizedRecommendations(){const[data,setData]=useState<Payload|null>(null),[error,setError]=useState('');useEffect(()=>{fetch('/api/recommendations',{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error('No se pudieron cargar las recomendaciones.');setData(await response.json())}).catch(value=>setError(value.message))},[]);if(error)return null;if(!data)return <div className="h-40 animate-pulse rounded-2xl bg-muted"/>;return <section className="space-y-5" aria-labelledby="recommendations-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><Badge variant="secondary" className="mb-2 gap-1"><Sparkles className="size-3"/>Personalizado</Badge><h2 id="recommendations-title" className="text-2xl font-bold">Tu siguiente mejor paso</h2></div><p className="max-w-xl text-xs text-muted-foreground">{data.explanation.method} Señales: {Object.entries(data.explanation.signals).map(([key,value])=>`${key} ${value}`).join(' · ')}</p></div><div className="grid gap-4 md:grid-cols-2">{data.continueItem&&<ActionCard icon={Flame} title={data.continueItem.title} description={data.continueItem.description} reason={data.continueItem.reason} href={data.continueItem.href}/>}<ActionCard icon={ArrowRight} title={data.nextStep.title} description={data.nextStep.description} reason={data.nextStep.reason} href={data.nextStep.href}/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.recommendations.slice(0,8).map(item=>{const Icon=icons[item.kind];return <Card key={`${item.kind}-${item.id}`} className="overflow-hidden"><CardContent className="flex h-full flex-col p-4">{item.imageUrl&&<img src={item.imageUrl} alt="" className="mb-3 aspect-video w-full rounded-lg border object-cover" loading="lazy"/>}<Badge variant="outline" className="mb-2 w-fit gap-1"><Icon className="size-3"/>{labels[item.kind]}</Badge><h3 className="font-semibold">{item.title}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{item.description}</p><p className="mt-3 text-xs text-primary">{item.reasons[0]}</p><Button asChild variant="ghost" size="sm" className="mt-auto justify-start px-0"><Link href={item.href}>Ver recomendación <ArrowRight className="ml-2 size-3"/></Link></Button></CardContent></Card>})}</div></section>}
function ActionCard({icon:Icon,title,description,reason,href}:{icon:typeof Flame;title:string;description:string;reason:string;href:string}){return <Card className="border-primary/20"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-lg"><Icon className="size-5 text-primary"/>{title}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{description}</p><p className="mt-2 text-xs text-primary">Por qué: {reason}</p><Button asChild size="sm" className="mt-4"><Link href={href}>Continuar <ArrowRight className="ml-2 size-4"/></Link></Button></CardContent></Card>}
