import mongoose, { Document, Schema } from 'mongoose';

export interface ICreativeProject extends Document {
  userId:string;name:string;brief:string;audience:string;status:'active'|'archived';
  budget:{limitCredits:number|null;limitUsd:number|null;warningPercent:number;approvalCredits:number|null;approvalUsd:number|null};
  reviewStatus:'draft'|'review'|'approved'|'published';
  outputContractId:string|null;
  collaborators:Array<{email:string;userId:string|null;role:'editor'|'reviewer';invitedBy:string;createdAt:Date}>;
  reviewComments:Array<{userId:string|null;authorName:string;body:string;jobId:string|null;source:'member'|'client';createdAt:Date}>;
  changeRequests:Array<{userId:string|null;authorName:string;body:string;jobId:string|null;status:'open'|'resolved';resolvedBy:string|null;createdAt:Date;resolvedAt:Date|null}>;
  activity:Array<{actorUserId:string|null;actorName:string;action:string;detail:string;createdAt:Date}>;
  brand:{name:string;voice:string;colors:string[];headingFont:string;bodyFont:string};
  prompts:Array<{title:string;content:string;versionId:string|null;addedAt:Date}>;
  assets:Array<{jobId:string;kind:'image'|'video'|'project';provider:string;url:string|null;addedAt:Date}>;
  components:Array<{componentId:string;title:string;kind:string;addedAt:Date}>;
  decisions:Array<{text:string;reason:string;type:'prompt'|'model'|'result'|'publication'|'note';status:'approved'|'rejected'|'published'|'recorded';actorUserId:string;actorName:string;promptVersionId:string|null;promptVersionNumber:number|null;provider:string|null;jobId:string|null;publicationId:string|null;publicationName:string|null;createdAt:Date}>;
  exports:Array<{format:string;createdAt:Date}>;createdAt:Date;updatedAt:Date;
}
const BrandSchema=new Schema({name:{type:String,default:'',maxlength:120},voice:{type:String,default:'',maxlength:500},colors:{type:[String],default:[]},headingFont:{type:String,default:'',maxlength:100},bodyFont:{type:String,default:'',maxlength:100}},{_id:false});
const BudgetSchema=new Schema({limitCredits:{type:Number,default:null,min:0},limitUsd:{type:Number,default:null,min:0},warningPercent:{type:Number,default:80,min:1,max:100},approvalCredits:{type:Number,default:null,min:0},approvalUsd:{type:Number,default:null,min:0}},{_id:false});
const CollaboratorSchema=new Schema({email:{type:String,required:true,lowercase:true,trim:true,maxlength:320},userId:{type:String,default:null},role:{type:String,enum:['editor','reviewer'],required:true},invitedBy:{type:String,required:true},createdAt:{type:Date,default:Date.now}},{_id:true});
const CommentSchema=new Schema({userId:{type:String,default:null},authorName:{type:String,required:true,maxlength:120},body:{type:String,required:true,maxlength:2000},jobId:{type:String,default:null},source:{type:String,enum:['member','client'],default:'member'},createdAt:{type:Date,default:Date.now}},{_id:true});
const ChangeRequestSchema=new Schema({userId:{type:String,default:null},authorName:{type:String,required:true,maxlength:120},body:{type:String,required:true,maxlength:2000},jobId:{type:String,default:null},status:{type:String,enum:['open','resolved'],default:'open'},resolvedBy:{type:String,default:null},createdAt:{type:Date,default:Date.now},resolvedAt:{type:Date,default:null}},{_id:true});
const ActivitySchema=new Schema({actorUserId:{type:String,default:null},actorName:{type:String,required:true,maxlength:120},action:{type:String,required:true,maxlength:80},detail:{type:String,required:true,maxlength:500},createdAt:{type:Date,default:Date.now}},{_id:true});
const CreativeProjectSchema=new Schema<ICreativeProject>({userId:{type:String,required:true,index:true},name:{type:String,required:true,maxlength:160},brief:{type:String,default:'',maxlength:5000},audience:{type:String,default:'',maxlength:1500},status:{type:String,enum:['active','archived'],default:'active',index:true},budget:{type:BudgetSchema,default:{}},reviewStatus:{type:String,enum:['draft','review','approved','published'],default:'draft',index:true},outputContractId:{type:String,default:null,index:true},collaborators:{type:[CollaboratorSchema],default:[]},reviewComments:{type:[CommentSchema],default:[]},changeRequests:{type:[ChangeRequestSchema],default:[]},activity:{type:[ActivitySchema],default:[]},brand:{type:BrandSchema,default:{}},prompts:{type:[new Schema({title:{type:String,required:true,maxlength:160},content:{type:String,required:true,maxlength:20000},versionId:{type:String,default:null},addedAt:{type:Date,default:Date.now}},{_id:true})],default:[]},assets:{type:[new Schema({jobId:{type:String,required:true},kind:{type:String,enum:['image','video','project'],required:true},provider:{type:String,required:true},url:{type:String,default:null},addedAt:{type:Date,default:Date.now}},{_id:true})],default:[]},components:{type:[new Schema({componentId:{type:String,required:true},title:{type:String,required:true},kind:{type:String,required:true},addedAt:{type:Date,default:Date.now}},{_id:true})],default:[]},decisions:{type:[new Schema({text:{type:String,required:true,maxlength:1000},reason:{type:String,default:'',maxlength:1000},type:{type:String,enum:['prompt','model','result','publication','note'],default:'note'},status:{type:String,enum:['approved','rejected','published','recorded'],default:'recorded'},actorUserId:{type:String,default:''},actorName:{type:String,default:'Usuario'},promptVersionId:{type:String,default:null},promptVersionNumber:{type:Number,default:null},provider:{type:String,default:null},jobId:{type:String,default:null},publicationId:{type:String,default:null},publicationName:{type:String,default:null},createdAt:{type:Date,default:Date.now}},{_id:true})],default:[]},exports:{type:[new Schema({format:{type:String,required:true,maxlength:40},createdAt:{type:Date,default:Date.now}},{_id:true})],default:[]},createdAt:{type:Date,default:Date.now,index:true},updatedAt:{type:Date,default:Date.now}},{versionKey:false});
CreativeProjectSchema.index({userId:1,updatedAt:-1});
CreativeProjectSchema.index({'collaborators.email':1,updatedAt:-1});
export default mongoose.models.CreativeProject||mongoose.model<ICreativeProject>('CreativeProject',CreativeProjectSchema,'creative_projects');
